system:
  hb_period: 0.15
  rf_slot_max: 1.0        # сек, максимум безперервного часу в RF
  rf_cooldown: 0.5        # сек, захист від частих входів у RF
  rf_triggers:
    debt_threshold: 5     # когнітивний борг (умовні одиниці)
    entropy_threshold: 0.7


subjects:
  PID0:
    T1_multiplier: 1.0
  Root:
    T1_multiplier: 1.0

kem:
  kernel_max: 1024
  subject_max: 4096
  policy: drop_oldest

scheduler:
  rf_trigger_debt: 4
  rf_max_cycles: 2
  kernel_overload_threshold: 6
  fairness_decay: 0.85